services:
    server:
        container_name: minecraft-server
        build: .
        ports:
            - 25565:25565
        volumes:
            - ./world:/app/world
            - ./ops.json:/app/ops.json
            - ./server.properties:/app/server.properties
